### ISSUE TITLE
经测试webssh进程无法正常保活

### ISSUE THREAD

**Issue by secexe** [zjccc1999/serv00-play-baohuo#1]
如题，通过serv00-play脚本能正常启动webssh服务，但通过您的serv00-ql.sh启动不起来，我看了下这是play脚本的启动命令
![image](https://github.com/user-attachments/assets/27f8d3f1-b7f7-45e8-83e1-74bada873ba3)
这里带的有端口参数等

您的脚本这里不带参数
![image](https://github.com/user-attachments/assets/faf1980d-ad19-4fbf-ac37-2740188b8728)
我猜测可能是没参数无法正常启动？

**Comment by zjccc1999** [comment]
你自己改改吧。我懒得搞了

**Comment by zjccc1999** [comment]
修复了
