### ISSUE TITLE
青龙版本能不能改成直接读取脚本目录里的serv00.json文件

### ISSUE THREAD

**Issue by jjwjs** [zjccc1999/serv00-play-baohuo#3]
青龙版本能不能改成直接读取脚本目录里的serv00.json文件，这样自己内网青龙也不容易泄露

**Comment by zjccc1999** [comment]
# 原来从远程获取的代码  和脚本同目录
# CONFIG_URL="xxxxxxx/serv00.json"
# CONFIG_JSON=$(curl -s "$CONFIG_URL")

# 改为从本地读取配置文件内容（以下是新代码）
CONFIG_FILE="serv00.json"
if [ -f "$CONFIG_FILE" ]; then
    CONFIG_JSON=$(cat "$CONFIG_FILE")
else
    echo "配置文件 $CONFIG_FILE 不存在，脚本无法继续执行"
    exit 1
fi

**Comment by zjccc1999** [comment]
test 分支也有个脚本 功能差不多，方法不一样
